### NumPy's [Quickstart Tutorial](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)

In [1]:
import numpy as np

In [2]:
arr = [[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 10, 11]]
np_arr = np.array(arr)

print(np_arr)
print(type(np_arr))
print("Shape: " + str(np_arr.shape))
print("Rank (number of axes/dimensions): " + str(np_arr.ndim))
print("Size: " + str(np_arr.size))
print("Type: " + str(np_arr.dtype))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
<class 'numpy.ndarray'>
Shape: (4, 3)
Rank (number of axes/dimensions): 2
Size: 12
Type: int64


NumPy arrays automatically convert elements to a single type that can be specified: 

In [3]:
np_arr = np.array([1.5, 2.5, 3, 4, 5])
print(np_arr)
print("Type: " + str(np_arr.dtype))

[1.5 2.5 3.  4.  5. ]
Type: float64


In [4]:
np_arr = np.array([1.5, 2.5, 3, 4, 5], dtype=int)
print(np_arr)
print("Type: " + str(np_arr.dtype))

[1 2 3 4 5]
Type: int64


Other ways to create NumPy arrays:

In [5]:
print(np.zeros(5))
print(np.ones((2, 4)))
print(np.empty(4))

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 0.00000000e+000 -2.31584193e+077  2.16272868e-314  2.78136358e-309]


In [6]:
print(np.arange(20, 30, 3))           # 3 represents step size
print(np.linspace(20, 30, 3))         # 3 represents number of elements
print(np.arange(24).reshape(2, 3, 4)) # 2x3x4 array with elements from 0-23

[20 23 26 29]
[20. 25. 30.]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Operations on NumPy arrays:

In [7]:
a = np.array((2, 4, 6, 8))
b = np.array([1, 2, 3, 4])
# Both a and b must be same length or one must be an array/tuple of length 1
print(a + b)
print(a * b)
print(a ** 2)
print(b * [3, 6, 9, 12])
print(b * (3))
print(a < 5)
print(b % 2 == 0)

a *= b # changes the value of a
print(a)
# Note: 'a + 0.1' works but 'a += 0.1' produces a casting error
print(a + 0.1) # Converts to float because it's more precise than int

[ 3  6  9 12]
[ 2  8 18 32]
[ 4 16 36 64]
[ 3 12 27 48]
[ 3  6  9 12]
[ True  True False False]
[False  True False  True]
[ 2  8 18 32]
[ 2.1  8.1 18.1 32.1]


Matrix dot products: 

In [8]:
a = np.array([[1, 1],
              [0, 1]])
b = np.array([[2, 0], 
              [3, 4]])
print("Multiplying together: \n" + str(a * b))
print("Actual dot product: \n" + str(a.dot(b)))
print("Alternative dot product: \n" + str(np.dot(a, b)))

Multiplying together: 
[[2 0]
 [0 4]]
Actual dot product: 
[[5 4]
 [3 4]]
Alternative dot product: 
[[5 4]
 [3 4]]


Unary operations: 

In [9]:
a = np.array([2, 3, 4])
print(a.sum())
print(a.max() - a.min())

b = np.array([[2, 3, 4], 
              [5, 6, 7], 
              [8, 9, 10], 
              [11, 12, 13]])
print(b.sum())
print(b.sum(axis=0)) # Sum across columns
print(b.sum(axis=1)) # Sum across rows

9
2
90
[26 30 34]
[ 9 18 27 36]


Universal functions (ufunc): 

In [10]:
a = np.arange(6)
print(np.square(a))
print(np.sqrt(a))
print(np.add(a, np.arange(2, 8)))

[ 0  1  4  9 16 25]
[0.         1.         1.41421356 1.73205081 2.         2.23606798]
[ 2  4  6  8 10 12]


Index, slicing, and iterating: 

In [11]:
a = np.arange(6)
print(a[2])
print(a[3:5])
print(a[::-1])
a[:4:2] = -1
print(a[a < 2])
print('\n')

def f(x, y):
    return x * 10 + y
b = np.fromfunction(f, (3, 4)) # Another way of initializing array
print(b)
print(str(b[2,3]) + " " + str(b[1][2]))
print(b[::2, 3:1:-1])
# b[0, ...] also works, where ... represents :,:,... as many times as needed
print('\n')

for row in b:
    print(row)
for num in b.flat:
    print(num)

2
[3 4]
[5 4 3 2 1 0]
[-1  1 -1]


[[ 0.  1.  2.  3.]
 [10. 11. 12. 13.]
 [20. 21. 22. 23.]]
23.0 12.0
[[ 3.  2.]
 [23. 22.]]


[0. 1. 2. 3.]
[10. 11. 12. 13.]
[20. 21. 22. 23.]
0.0
1.0
2.0
3.0
10.0
11.0
12.0
13.0
20.0
21.0
22.0
23.0


Shape manipulation: 

In [12]:
a = np.arange(6)
print(a)
a = a.reshape(2, 3)  # Does not modify the array, returns a new one
print(a)
print(a.transpose()) # Flips rows and columns
a = a.ravel()
print(a)
a.resize(2, 3)       # Modifies the array unlike reshape, returns nothing
print(a)
print(a.reshape(3, -1)) # Calculates correct number of columns (doesn't work with resize function)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [13]:
a = np.arange(4).reshape(2, 2)
b = np.arange(4, 8).reshape(2, 2)
print(a)
print(b)
print('\n')
print(np.vstack((a, b)))
print(np.hstack((a, b)))
print('\n')
print(np.column_stack((a, [4, 5], [6, 7]))) # Adds 1D arrays as columns to a 2D array

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0 1 4 5]
 [2 3 6 7]]


[[0 1 4 6]
 [2 3 5 7]]


In [14]:
a = np.arange(12).reshape(3, 4)
print(a)
print(np.hsplit(a, 2))      # Splits into two arrays
print(np.hsplit(a, (1, 3))) # Splits after 1st and 3rd column
print(np.vsplit(a, 3))      # Splits vertically

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0],
       [4],
       [8]]), array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


Pass by value vs. pass by reference, etc: 

In [15]:
a = np.arange(6)
b = a.view() # b is a view of a's data (is able to modify data but not things like a.shape)
print(b is a)
print(b.base is a)
b[2:4] *= -1
print(a)

b = a[-2:] # b[:] is a view of a
b[:] = 10  # Note: b = 10 would not work, it would change b to type int
print(a)

c = a.copy()
c[0] = 999
print(a)
# a.view() produces a shallow copy whereas a.copy() produces a deep copy

False
True
[ 0  1 -2 -3  4  5]
[ 0  1 -2 -3 10 10]
[ 0  1 -2 -3 10 10]


Broadcasting: Allowing functions to deal with arrays that aren't exactly the same shape. Arrays are lined up by trailing axes and each dimension must be the same length or one of them has to be length 1. If the number of dimensions doesn't match, a '1' will be prepended to the smaller array until they match. 

In [16]:
a = np.arange(3)
b = np.array([2, 2, 2])
print(a * b)
print(a * 2)
# Both methods work

# Similarly, A * B below would produce the following dimensions: 
# A      (4d array):  8 x 1 x 6 x 1
# B      (3d array):      7 x 1 x 5
# Result (4d array):  8 x 7 x 6 x 5

[0 2 4]
[0 2 4]


More ways of indexing:

In [17]:
a = np.arange(6) ** 2
print(a)
print(a[np.array([1, 4, 2])])
print(a[np.array([[2, 4], [1, 3]])])
a[[3, 4, 5]] = -1
print(a)
a[[0, 1, 1]] = [100, 200, 300] # 200 and 300 both assigned to index 1
print(a)
a[[0, 1, 1]] += 100 # Only increases index 1 once
print(a)

[ 0  1  4  9 16 25]
[ 1 16  4]
[[ 4 16]
 [ 1  9]]
[ 0  1  4 -1 -1 -1]
[100 300   4  -1  -1  -1]
[200 400   4  -1  -1  -1]


In [18]:
a = np.arange(6)
b = a % 2 == 0
print(b)
print(a[b])
a[b] *= -1
print(a)
print(a[[True, True, True, False, False, True]])

[ True False  True False  True False]
[0 2 4]
[ 0  1 -2  3 -4  5]
[ 0  1 -2  5]


The ix_() function to combine vectors:

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5])
c = np.array([6, 7, 8, 9])
ax, bx, cx = np.ix_(a, b, c)
print(ax)
print(bx)
print(cx)
print(ax.shape, bx.shape, cx.shape)
result = ax + bx * cx
print(result)
print(result[1, 0, 3])

[[[1]]

 [[2]]

 [[3]]]
[[[4]
  [5]]]
[[[6 7 8 9]]]
(3, 1, 1) (1, 2, 1) (1, 1, 4)
[[[25 29 33 37]
  [31 36 41 46]]

 [[26 30 34 38]
  [32 37 42 47]]

 [[27 31 35 39]
  [33 38 43 48]]]
38


Other:

In [20]:
a = np.arange(30)
a.shape = 5, -1, 2 # Automatically determine correct shape
print(a.shape) 

a = np.array([2, 4, 6, 8])
b = np.array([1, 3, 5, 7])
print(np.vstack([a, b])) # Joining vectors into one array
print(np.hstack([a, b]))
print(np.vstack([a, a, a]))

(5, 3, 2)
[[2 4 6 8]
 [1 3 5 7]]
[2 4 6 8 1 3 5 7]
[[2 4 6 8]
 [2 4 6 8]
 [2 4 6 8]]
